# Generated by Django 5.0.3 on 2024-05-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_employee_dept_id_alter_employee_role_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='dept_id',
            new_name='dept',
        ),
    ]
