# Generated by Django 5.0.3 on 2024-05-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_dept_id_role_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='dept',
        ),
    ]
