# Generated by Django 5.0.3 on 2024-05-24 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_employee_dept_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.department'),
            preserve_default=False,
        ),
    ]
