# Generated by Django 5.0.3 on 2024-05-26 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_department_location_employee_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
        migrations.AddField(
            model_name='employee',
            name='loc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.location'),
            preserve_default=False,
        ),
    ]
