# Generated by Django 5.0.3 on 2024-05-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_location_remove_employee_location_employee_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='loc',
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
